title: Kasia Wrona # your name (or website title) here
logo: "/images/unnamed1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist at Justtag Group
  <br><br>Proficient in writing and optimising SQL queries, data visualisation with Tableau and data modeling with Python. My main area of instrest is machine learning.
  <br><br>
  <a href="https://www.linkedin.com/in/katarzyna-anna-wrona/">LinkedIn Profile</a> 
  <br>
  <a href="https://github.com/kwro">GitHub Repo</a> 
  <br>
  <a href="https://public.tableau.com/app/profile/kasia.wrona/">Tableau Public</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
