title: Kasia Wrona # your name (or website title) here
logo: "/images/Screen Shot 2020-09-14 at 21.05.25.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science enthusiast
  <br>
  Experiance gained in finance and marketing departments in international corporation as well as European start-up companies.
  <br><br>
  Currently combining Data Analyst and Data Scientist position in Justtag Group, Polish start-up company in marketing field.
  <br><br>
  <a href="https://www.linkedin.com/in/katarzyna-anna-wrona/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
